services:
  # Backend WebSocket
  - type: web
    name: limite-limite-backend
    env: docker
    dockerfilePath: ./Dockerfile  # À la racine
    context: .  # Contexte à la racine (important !)
    envVars:
      - key: PORT
        value: 8080
    plan: free



  # Frontend (optionnel si tu veux séparer)
  - type: web
    name: limite-limite-frontend
    env: static
    buildCommand: echo "No build needed"
    staticPublishPath: ./frontend
    plan: free