services:
  # Backend WebSocket
  - type: web
    name: limite-limite-backend
    env: docker
    dockerfilePath: ./backend-pwa/Dockerfile
    envVars:
      - key: PORT
        value: 8080
    plan: free


  # Frontend (optionnel si tu veux s√©parer)
  - type: web
    name: limite-limite-frontend
    env: static
    buildCommand: echo "No build needed"
    staticPublishPath: ./frontend
    plan: free